repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
    - id: nbqa-isort
      args: [--profile=black]
    - id: nbqa-black
    - id: nbqa-pyupgrade
      args: [--py38-plus]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
    args: [--fix, --disable, MD013]
