repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
    - id: nbqa-black
    - id: nbqa-pyupgrade
      args: [--py38-plus]
    - id: nbqa-isort
      args: ["--profile", "black"]
    - id: nbqa-autopep8
